name: Daily Test Build TileDB-Py Against Core

on: [push]

# on:
#   schedule:
#     # runs every day at 5:00 UTC (1:00AM EST / Midnight CST)
#     - cron: "5 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TILEDB_VERSION: dev

    steps:
    # - name: Set up Python
    #   uses: actions/setup-python@v2

    # - name: Print Python version
    #   run: |
    #     which python
    #     which pip
    #     python --version

    # - name: Print env
    #   run: printenv

    - name: Checkout TileDB-Py `dev`
      uses: actions/checkout@v2

    # - name: Install dependencies
    #   run: python -m pip install --upgrade -r misc/requirements_ci.txt

    # - name: Build TileDB-Py
    #   run: |
    #     python setup.py build_ext --inplace --werror
    #     python setup.py install

    # - name: Test TileDB-Py
    #   run: pytest -vv

    - name: FAIL
      run: exit 1
    
    - name: Get current date
      if: failure()
      id: date
      run: echo "::set-output name=date::$(date +'%m-%d-%Y')"
    
    - name: Create PR if failed
      uses: peter-evans/create-pull-request@v3
      if: failure()
      with:
        commit-message: Update report
        signoff: false
        branch: example-patches
        delete-branch: true
        title: '[TEST] Failed Nightly Build for ${{ steps.date.outputs.date }}'
        body: |
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        draft: false

    # - name: Create Clubhouse story if PR was created
    #   uses: singingwolfboy/create-linked-clubhouse-story@v1.8
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
    #     clubhouse-token: ${{ secrets.CLUBHOUSE_TOKEN }}
    #     project-name: Engineering
    #     opened-state-name: Started
    #     merged-state-name: Done
    #     closed-state-name: Abandoned
    #     comment-template: >-
    #       Thanks for the pull request! [I've created a Clubhouse story
    #       for you.]({{{ story.app_url }}})
