name: Daily Test Build TileDB-Py Against Core

on: [push]

# on:
#   schedule:
#     # runs every day at 5:00 UTC (1:00AM EST / Midnight CST)
#     - cron: "5 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TILEDB_VERSION: dev

    steps:
    # - name: Set up Python
    #   uses: actions/setup-python@v2

    # - name: Print Python version
    #   run: |
    #     which python
    #     which pip
    #     python --version

    # - name: Print env
    #   run: printenv

    - name: Checkout TileDB-Py `dev`
      uses: actions/checkout@v2

    # - name: Install dependencies
    #   run: python -m pip install --upgrade -r misc/requirements_ci.txt

    # - name: Build TileDB-Py
    #   run: |
    #     python setup.py build_ext --inplace --werror
    #     python setup.py install

    # - name: Test TileDB-Py
    #   run: pytest -vv

    - name: FAIL
      run: exit 1
    
    - name: Get current date
      if: failure()
      id: date
      run: echo "::set-output name=date::$(date +'%m-%d-%Y')"
  
    - name: Create new branch for PR
      uses: peterjgrainger/action-create-branch@v2.0.1
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: 'failed-night-build-${{ steps.date.outputs.date }}'

    - name: Create PR if failed
      uses: peter-evans/create-pull-request@v3
      if: failure()
      with:
        branch: 'failed-night-build-${{ steps.date.outputs.date }}'
        title: '[TEST] Failed Nightly Build for ${{ steps.date.outputs.date }}'
        body: |
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request